# Generated by Django 2.0.3 on 2018-04-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfacts', '0003_auto_20180409_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
