# Generated by Django 2.0.3 on 2018-04-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfacts', '0005_auto_20180409_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
